version: '3'
services:
 user_service:
  container_name: user_service
  image: user
  ports:
   - "5151:5151"
  volumes:
   - "$PWD/user_service/node_modules:/app/node_modules"
  build:
   context: user_service
  networks:
   - net
 api_gateway:
  container_name: nginx
  image: nginx
  ports:
   - "8084:80"
  build:
   context: api_gateway
  networks:
   - net
networks:
 net:
